# Generated by Django 3.2.7 on 2021-09-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tagline', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_name', models.CharField(max_length=250)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railapp.end')),
                ('journey_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railapp.date')),
                ('journey_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railapp.day')),
                ('journey_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railapp.status')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railapp.start')),
            ],
        ),
    ]
