# Generated by Django 3.2.7 on 2021-09-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railapp', '0002_auto_20210920_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='railschedule',
            name='journey_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='railapp.time'),
            preserve_default=False,
        ),
    ]
