# Generated by Django 3.2.7 on 2021-09-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railapp', '0003_auto_20210920_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='journey_day',
        ),
        migrations.RenameField(
            model_name='railschedule',
            old_name='journey_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='railschedule',
            old_name='journey_day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='railschedule',
            old_name='journey_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='journey_time',
        ),
    ]
